"""Create models Estate, House

Revision ID: a05d468be74d
Revises: 
Create Date: 2024-02-14 21:45:26.744743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05d468be74d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('num_of_rooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('estate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], name=op.f('fk_houses_estate_id_estates')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    op.drop_table('estates')
    # ### end Alembic commands ###
